{{ config(materialized='table') }}

WITH fact_cte AS (
  SELECT 
    ROW_NUMBER() OVER (ORDER BY ASSET) AS FACT_ID, 
    HIGHLIMITPRICE,
    LOWLIMITPRICE,
    SECURITYID AS ASSET_ID, -- Assuming SECURITYID is the asset ID
    TO_CHAR(ACTIVATIONDATETIME, 'YYMMDD') AS ACTIVATIONDATETIME_ID,
    TO_CHAR(EXPIRATIONDATETIME, 'YYMMDD') AS EXPIRATIONDATETIME_ID,
    TO_CHAR(MATURITYDATE, 'YYMMDD') AS MATURITYDATE_ID,
    TO_CHAR(TRADEDATE, 'YYMMDD') AS TRADEDATE_ID
  FROM PUBLIC.CMEDATA_TABLE
)
SELECT *
FROM fact_cte
